// Code generated by Claude.ai

using FirstGame;

public class GameMap
{
    #region VARIABLES

    private const int DefaultWidth = 5;
    private const int DefaultHeight = 5;
    
    private readonly int _width;
    private readonly int _height;
    private Vector2Int _playerPosition;
    private readonly Location[,] _mapLocations;

    #endregion
    
    #region INTERNAL CLASSES
    public class Location
    {
        public string Description { get; set; }
        public bool IsAccessible { get; set; }
        public Dictionary<string, string> InteractiveObjects { get; set; }

        public Location(string description = "There's nothing here", bool isAccessible = true)
        {
            Description = description;
            IsAccessible = isAccessible;
            InteractiveObjects = new Dictionary<string, string>();
        }
    }

    #endregion
    
    #region CONSTRUCTOR
    
    public GameMap(int width, int height, Vector2Int startPosition)
    {
        CheckInputDimensions(ref width, ref height);

        _width = width;
        _height = height;
        _mapLocations = new Location[width, height];

        // Initialize all locations with default values
        for (int x = 0; x < width; x++)
        {
            for (int y = 0; y < height; y++)
            {
                _mapLocations[x, y] = new Location();
            }
        }

        // Set initial player position if valid
        if (IsValidPosition(startPosition))
        {
            _playerPosition = startPosition;
        }
        else
        {
            _playerPosition = new Vector2Int() ;
        }
    }
    
    #endregion

    #region METHODS

    private void CheckInputDimensions(ref int width , ref int height)
    {
        if (width <= 0 || height <= 0)
        {
            width = DefaultWidth;
            height = DefaultHeight;
        }
    }
    
    public Vector2Int GetPlayerPosition() => _playerPosition;

    /*
    // The method above does the same thing as this one:
    public (int x, int y) GetPlayerPosition()
    {
        return _playerPosition;
    }
    */

    public bool MovePlayer(string direction)
    {
        var newPosition = CalculateNewPosition(direction);
        
        if (IsValidPosition(newPosition) && _mapLocations[newPosition.X, newPosition.Y].IsAccessible)
        {
            _playerPosition = newPosition;
            return true;
        }
        return false;
    }

    private Vector2Int CalculateNewPosition(string direction)
    {
        // switch chooses from the possible cases, and then does the code inside.
        // It is a version of if for limited case scenarios
        
        Vector2Int newPosition = new Vector2Int();
        newPosition = _playerPosition;
        
        switch (direction.ToLower())
        {
            case "north":
                newPosition.Y += 1;
                break;
            case "south":
                newPosition.Y -= 1;
                break;
            case "west":
                newPosition.X -= 1;
                break;
            case "east":
                newPosition.X += 1;
                break;
            default:
                Console.WriteLine("That is not a valid direction");
                break;
        }

        return newPosition;
    }

    private bool IsValidPosition(Vector2Int position)
    {
        return position.X >= 0 && position.X < _width && 
               position.Y >= 0 && position.Y < _height;
    }

    public Location GetCurrentLocation()
    {
        return _mapLocations[_playerPosition.X, _playerPosition.Y];
    }

    public void SetLocationDescription(Vector2Int position, string description)
    {
        if (IsValidPosition(position))
        {
            _mapLocations[position.X, position.Y].Description = description;
        }
    }

    public void SetLocationAccessibility(Vector2Int position, bool isAccessible)
    {
        if (IsValidPosition(position))
        {
            _mapLocations[position.X, position.Y].IsAccessible = isAccessible;
        }
    }

    public void AddInteractiveObject(Vector2Int position, string objectName, string description)
    {
        if (IsValidPosition(position))
        {
            _mapLocations[position.X, position.Y].InteractiveObjects[objectName] = description;
        }
    }
    
    #endregion
}
