// Code generated by Claude.ai

using FirstGame;

public class GameMap
{
    #region REFERENCES

    private Game _game;
    private MapLocations _locations;
    
    #endregion
    
    #region VARIABLES

    private const int DefaultWidth = 5;
    private const int DefaultHeight = 5;
    
    private readonly int _width;
    private readonly int _height;
    private Vector2Int _playerPosition;

    #endregion
    
    #region CONSTRUCTOR
    
    public GameMap(Game game, int width, int height, Vector2Int startPosition)
    {
        _game = game;
        
        CheckInputDimensions(ref width, ref height);

        _width = width;
        _height = height;
        
        // Initialize all locations with default values
        _locations = new MapLocations(this);

        // Set initial player position if valid
        if (IsValidPosition(startPosition))
        {
            _playerPosition = startPosition;
        }
        else
        {
            _playerPosition = new Vector2Int() ;
        }
    }
    
    #endregion

    #region METHODS

    private void CheckInputDimensions(ref int width , ref int height)
    {
        if (width <= 0 || height <= 0)
        {
            width = DefaultWidth;
            height = DefaultHeight;
        }
    }
    
    public Vector2Int GetPlayerPosition() => _playerPosition;

    /*
    // The method above does the same thing as this one:
    public (int x, int y) GetPlayerPosition()
    {
        return _playerPosition;
    }
    */

    public bool MovePlayer(Direction direction)
    {
        var newPosition = CalculateNewPosition(direction);
        return SetPlayerPosition(newPosition);
    }

    public bool MovePlayer(Vector2Int targetPosition)
    {
        return SetPlayerPosition(targetPosition);
    }

    private bool SetPlayerPosition(Vector2Int targetPosition)
    {
        if (IsValidPosition(targetPosition))
        {
            _playerPosition = targetPosition;
            return true;
        }
        return false;
    }
    
    private Vector2Int CalculateNewPosition(Direction direction)
    {
        // switch chooses from the possible cases, and then does the code inside.
        // It is a version of if for limited case scenarios
        
        Vector2Int newPosition = new Vector2Int();
        newPosition = _playerPosition;
        
        switch (direction)
        {
            case Direction.North:
                newPosition.Y += 1;
                break;
            case Direction.South:
                newPosition.Y -= 1;
                break;
            case Direction.West:
                newPosition.X -= 1;
                break;
            case Direction.East:
                newPosition.X += 1;
                break;
            default:
                Console.WriteLine("That is not a valid direction");
                break;
        }

        return newPosition;
    }

    private bool IsValidPosition(Vector2Int position)
    {
        return position.X >= 0 && position.X < _width && 
               position.Y >= 0 && position.Y < _height;
    }

    public string GetCurrentLocationName()
    {
        // The better way of doing this is presented in the method below
        if (_locations.Locations.ContainsKey(_playerPosition))
        {
            return _locations.Locations[_playerPosition].Name;
        }

        return "the middle of nowhere.";
    }
    
    public string GetCurrentLocationDescription()
    {
        // This is the better way of doing that thing above
        if (_locations.Locations.TryGetValue(_playerPosition, out MapLocationData location))
        {
            return location.Description;
        }

        return "I told you, there is nothing here!";
    }

    public void InteractWithCurrentLocation()
    {
        if (!_locations.Locations.TryGetValue(_playerPosition, out MapLocationData location) 
            || !location.IsInteractable)
        {
            Console.WriteLine("There is nothing to do here");
            return;
        }

        Interaction interaction = location.Interaction;
        interaction.Choose();
    }
    
    #endregion
}

public enum Direction
{
    East,
    North,
    West,
    South,
    NorthEast,
    NorthWest,
    SouthEast,
    SouthWest,
    Up,
    Down,
    Inside,
    Outside,
    Right,
    Forward,
    Left,
    Back
}

